using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LANMIC_ComBank_Interface.Models.CombankModels
{
    public class PaymentRequest
    {
        public string inStatus { get; set; }
        public string cbcReference { get; set; }
        public string inputChanel { get; set; }
        public string inChanelIP32 { get; set; }
        public string inOutFlag { get; set; }
        public string priorityFlag { get; set; }
        public string processChanel { get; set; }
        public string msgType { get; set; }
        public string accountFlag { get; set; }
        public string stpFlag { get; set; }
        public string sancFlag { get; set; }
        public string inputUser { get; set; }
        public string inDate { get; set; }
        public string recDate { get; set; }
        public string holdate { get; set; }
        public string reference { get; set; }
        public string fxReference { get; set; }
        public string valDate { get; set; }
        public string currCode { get; set; }
        public string amount { get; set; }
        public string department { get; set; }
        public string instCur { get; set; }
        public string instAmt { get; set; }
        public string exchangeRate { get; set; }
        public string messIndex { get; set; }
        public string messTotal { get; set; }
        public string instrCode { get; set; }
        public string trnRefNbr { get; set; }
        public string trnCode { get; set; }
        public string retCode { get; set; }
        public string benBnkCode { get; set; }
        public string benBrnCode { get; set; }
        public string trnType { get; set; }
        public string benInstBIC { get; set; }
        public string benefBIC2 { get; set; }
        public string beneAcTyp { get; set; }
        public string benefAcct { get; set; }
        public string beneName { get; set; }
        public string beneAdd1 { get; set; }
        public string beneAdd2 { get; set; }
        public string beneAdd3 { get; set; }
        public string purpcode { get; set; }
        public string particular { get; set; }
        public string orgBkCode { get; set; }
        public string orgBrCode { get; set; }
        public string orgBIC { get; set; }
        public string orgAcTyp { get; set; }
        public string orgAccount { get; set; }
        public string orgName { get; set; }
        public string orgAdd1 { get; set; }
        public string orgAdd2 { get; set; }
        public string orgAdd3 { get; set; }
        public string furInstr { get; set; }
        public string secCheck { get; set; }
        public string filler { get; set; }
        public string orgDate { get; set; }
        public string ordInsBIC { get; set; }
        public string senCorBIC { get; set; }
        public string recCorBIC { get; set; }
        public string thrRemBIC { get; set; }
        public string interBIC { get; set; }
        public string chgDetail { get; set; }
        public string detPaymnt { get; set; }
        public string senToRec { get; set; }
        public string bitMap { get; set; }
        public string priActNo { get; set; }
        public string beneCard { get; set; }
        public string desAccNo { get; set; }
        public string cardPAN { get; set; }
        public string cardAcct { get; set; }
        public string cdDesActNm { get; set; }
        public string cdOrgActNm { get; set; }
        public string proCode { get; set; }
        public string trnMisDate { get; set; }
        public string sysTrcNbr { get; set; }
        public string locTrnTime { get; set; }
        public string locTrnDate { get; set; }
        public string setleDate { get; set; }
        public string capDate { get; set; }
        public string marchType { get; set; }
        public string acqInsCode { get; set; }
        public string retRefNo { get; set; }
        public string cardAccpTm { get; set; }
        public string cardAccpId { get; set; }
        public string cardAccNm { get; set; }
        public string cardCurCod { get; set; }
        public string addTermDtl { get; set; }
        public string msgAuthCd { get; set; }
        public string efttlvData { get; set; }
        public string debtorNm { get; set; }
        public string dbTitle { get; set; }
        public string dbFrstNm { get; set; }
        public string dbSecNm { get; set; }
        public string dbLstNm { get; set; }
        public string dbDOB { get; set; }
        public string dbProvDOB { get; set; }
        public string dbCityDOB { get; set; }
        public string dbCntDOB { get; set; }
        public string dbCntRes { get; set; }
        public string dbWkPhone { get; set; }
        public string dbHmPhone { get; set; }
        public string dbMobPhone { get; set; }
        public string dbFax { get; set; }
        public string dbEmail { get; set; }
        public string dbBIC { get; set; }
        public string dbLEI { get; set; }
        public string dbOthIdent { get; set; }
        public string dbSchCode { get; set; }
        public string dbSchName { get; set; }
        public string dbCntCode { get; set; }
        public string dbDept { get; set; }
        public string dbSubDept { get; set; }
        public string dbStrtNam { get; set; }
        public string dbBuildNo { get; set; }
        public string dbBuildNam { get; set; }
        public string dbFloor { get; set; }
        public string dbPosBox { get; set; }
        public string dbRoom { get; set; }
        public string dbPostCod { get; set; }
        public string dbTownNm { get; set; }
        public string dbLocNam { get; set; }
        public string dbDistNm { get; set; }
        public string dbCntSubDv { get; set; }
        public string dbAddLn { get; set; }
        public string dbIBAN { get; set; }
        public string dbOthActID { get; set; }
        public string creidNm { get; set; }
        public string crTitle { get; set; }
        public string crFrstNm { get; set; }
        public string crSecNm { get; set; }
        public string crLstNm { get; set; }
        public string crDOB { get; set; }
        public string crProvDOB { get; set; }
        public string crCityDOB { get; set; }
        public string crCntDOB { get; set; }
        public string crCntRes { get; set; }
        public string crWkPhone { get; set; }
        public string crHomPhone { get; set; }
        public string crMobPhone { get; set; }
        public string crFax { get; set; }
        public string crEmail { get; set; }
        public string crBIC { get; set; }
        public string crLEI { get; set; }
        public string crOthIdent { get; set; }
        public string crSchCode { get; set; }
        public string crSchName { get; set; }
        public string crCntCode { get; set; }
        public string crDept { get; set; }
        public string crSubDept { get; set; }
        public string crStrtNam { get; set; }
        public string crBuildNo { get; set; }
        public string crBuildNam { get; set; }
        public string crFloor { get; set; }
        public string crPosBox { get; set; }
        public string crRoom { get; set; }
        public string crPostCod { get; set; }
        public string crTownNm { get; set; }
        public string crLocNam { get; set; }
        public string crDistNm { get; set; }
        public string crCntSubDv { get; set; }
        public string crAddLn { get; set; }
        public string crIBAN { get; set; }
        public string crOthActID { get; set; }
        public string posentCode { get; set; }
        public string posconCode { get; set; }
    }
}
