using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LANMIC_ComBank_Interface.Models.SageModels
{
    public class SageBanksAPIModel
    {
        public string BankCode { get; set; }
        public string Description { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public string ZipPostalCode { get; set; }
        public string Contact { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string TransitNumber { get; set; }
        public bool Multicurrency { get; set; }
        public string StatementCurrency { get; set; }
        public bool Status { get; set; }
        public object InactiveDate { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccount { get; set; }
        public string WriteOffAccount { get; set; }
        public decimal ErrorSpread { get; set; }
        public DateTime LastMaintained { get; set; }
        public string FiscalYear { get; set; }
        public string FiscalPeriod { get; set; }
        public string LastReconciliationYear { get; set; }
        public int LastReconciliationPeriod { get; set; }
        public object LastReconciliationDate { get; set; }
        public decimal LastClosingStatementBalance { get; set; }
        public object ReconciliationDate { get; set; }
        public string StatementDate { get; set; }
        public decimal StatementBalance { get; set; }
        public decimal DepositsInTransit { get; set; }
        public decimal ChecksOutstanding { get; set; }
        public decimal BankErrors { get; set; }
        public decimal TotalNotPostedBankEntries { get; set; }
        public decimal WriteOffs { get; set; }
        public decimal ExchangeGain { get; set; }
        public decimal ExchangeLoss { get; set; }
        public decimal TotalDeposits { get; set; }
        public decimal TotalChecks { get; set; }
        public decimal DepositsToFiscalPeriod { get; set; }
        public decimal ChecksToFiscalPeriod { get; set; }
        public decimal DepositsInTransitToFiscalPeriod { get; set; }
        public decimal ChecksOutstandingToFiscalPeriod { get; set; }
        public bool CalculateFiscalPeriodData { get; set; }
        public string LastStatementDate { get; set; }
        public decimal DifferenceOfBankEntriesToFi { get; set; }
        public decimal ExchangeGainToFiscalPeriod { get; set; }
        public decimal ExchangeLossToFiscalPeriod { get; set; }
        public decimal BankErrorPendingToFiscalPer { get; set; }
        public decimal BankErrorToFiscalPeriod { get; set; }
        public decimal TotalNotPostedBankEntriesTo { get; set; }
        public string ChargesAccount { get; set; }
        public decimal CreditCardChargeSpread { get; set; }
        public decimal ExchangeRateDifferenceSpread { get; set; }
        public decimal AdjustedBookBalance { get; set; }
        public decimal AdjustedStatementBalance { get; set; }
        public bool BankReconciliationBalanced { get; set; }
        public decimal OutOfBalanceBy { get; set; }
        public int NextCheckSerialNumber { get; set; }
        public int NextDepositSlipNumber { get; set; }
        public int NextDepositUniquifier { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal BookBalance { get; set; }
        public string BankStatementType { get; set; }
        public decimal TotalWriteOffs { get; set; }
        public decimal TotalCreditCardCharges { get; set; }
        public decimal FiscalPeriodWriteOff { get; set; }
        public decimal FiscalPeriodCreditCardCharge { get; set; }
        public decimal SumOfWithdrawalTotalWriteOf { get; set; }
        public decimal SumOfDepositTotalWriteOffs { get; set; }
        public decimal SumOfWithdrawalFiscalWriteO { get; set; }
        public decimal SumOfDepositFiscalWriteOffs { get; set; }
        public string FunctionalCurrency { get; set; }
        public decimal TotalRemainingOutStanding { get; set; }
        public decimal FiscalRemainingOutStanding { get; set; }
        public decimal TotalRemainingInTransit { get; set; }
        public decimal FiscalRemainingInTransit { get; set; }
        public decimal FiscalWithdrawalClearedToCur { get; set; }
        public decimal FiscalDepositClearedToCurren { get; set; }
        public string TaxGroupDescription { get; set; }
        public string TaxAuthorizationDescription1 { get; set; }
        public string TaxAuthorizationDescription2 { get; set; }
        public string TaxAuthorizationDescription3 { get; set; }
        public string TaxAuthorizationDescription4 { get; set; }
        public string TaxAuthorizationDescription5 { get; set; }
        public string VendorTaxClassDescription1 { get; set; }
        public string VendorTaxClassDescription2 { get; set; }
        public string VendorTaxClassDescription3 { get; set; }
        public string VendorTaxClassDescription4 { get; set; }
        public string VendorTaxClassDescription5 { get; set; }
        public int NextSerialNumber { get; set; }
        public decimal DepositClearedwithExchangeRa { get; set; }
        public decimal WithdrawalsClearedwithExchangeR { get; set; }
        public decimal TotalWithdrawalBankErrors { get; set; }
        public decimal TotalWithdrawalWriteOffs { get; set; }
        public decimal TotalWithdrawalExchangeGain { get; set; }
        public decimal TotalWithdrawalExchangeLoss { get; set; }
        public decimal TotalWithdrawalCreditCardCha { get; set; }
        public decimal TotalWithdrawalCleared { get; set; }
        public decimal WithdrawalTotal { get; set; }
        public decimal FiscalWithdrawalBankErrors { get; set; }
        public decimal FiscalWithdrawalWriteOffs { get; set; }
        public decimal FiscalWithdrawalExchangeGain { get; set; }
        public decimal FiscalWithdrawalExchangeLoss { get; set; }
        public decimal FiscalWithdrawalCreditCardCh { get; set; }
        public decimal FiscalWithdrawalCleared { get; set; }
        public decimal FiscalWithdrawalTotal { get; set; }
        public decimal TotalDepositBankErrors { get; set; }
        public decimal TotalDepositWriteOffs { get; set; }
        public decimal TotalDepositExchangeGain { get; set; }
        public decimal TotalDepositExchangeLoss { get; set; }
        public decimal TotalDepositCreditCardCharge { get; set; }
        public decimal TotalDepositCleared { get; set; }
        public decimal DepositTotal { get; set; }
        public decimal FiscalDepositBankErrors { get; set; }
        public decimal FiscalDepositWriteOffs { get; set; }
        public decimal FiscalDepositExchangeGain { get; set; }
        public decimal FiscalDepositExchangeLoss { get; set; }
        public decimal FiscalDepositCreditCardCharg { get; set; }
        public decimal FiscalDepositCleared { get; set; }
        public decimal FiscalDepositTotal { get; set; }
        public decimal FiscalWithdrawalClearedToFut { get; set; }
        public decimal FiscalDepositClearedToFuture { get; set; }
        public decimal WithdrawalFunctionalTotal { get; set; }
        public decimal FiscalWithdrawalFunctionalTot { get; set; }
        public decimal DepositFunctionalTotal { get; set; }
        public decimal FiscalDepositFunctionalTotal { get; set; }
        public string TaxGroupCode { get; set; }
        public string TaxAuthorization1 { get; set; }
        public string TaxAuthorization2 { get; set; }
        public string TaxAuthorization3 { get; set; }
        public string TaxAuthorization4 { get; set; }
        public string TaxAuthorization5 { get; set; }
        public int VendorTaxClass1 { get; set; }
        public int VendorTaxClass2 { get; set; }
        public int VendorTaxClass3 { get; set; }
        public int VendorTaxClass4 { get; set; }
        public int VendorTaxClass5 { get; set; }
        public int DaysBeforeEligibleForClearin { get; set; }
        public string POSTDATE { get; set; }
        public string LSTPOSTDAT { get; set; }
        public decimal LastAvailableStatementBalance { get; set; }
        public string DefaultReconciliationDescripti { get; set; }
        public string BankingCloudAccount { get; set; }
        public bool BankingCloudConnected { get; set; }
        public int BankingCloudLastIndex { get; set; }
        public List<Bankcurrency> BankCurrencies { get; set; }
        public List<Banktransactionheader> BankTransactionHeader { get; set; }
        public List<Checkstock> CheckStocks { get; set; }
        //public object[] OFXTransactions { get; set; }
        //public string UpdateOperation { get; set; }
    }

    public class Bankcurrency
    {
        public string BankCode { get; set; }
        public string CurrencyCode { get; set; }
        public string CheckRateType { get; set; }
        public string DepositRateType { get; set; }
        public string ExchangeGainAccount { get; set; }
        public string ExchangeLossAccount { get; set; }
        public string RoundingAccount { get; set; }
        public string CurrencyDescription { get; set; }
        public string UpdateOperation { get; set; }
    }

    public class Banktransactionheader
    {
        public string BankCode { get; set; }
        public int TransactionHeaderSerial { get; set; }
        public int TransactionNumber { get; set; }
        public string SourceApplication { get; set; }
        public string TransactionType { get; set; }
        public int OldSerialNumber { get; set; }
        public string EntryType { get; set; }
        public string TransactionReference { get; set; }
        public string TransactionDescription { get; set; }
        public DateTime TransactionDate { get; set; }
        public string FiscalYear { get; set; }
        public string FiscalPeriod { get; set; }
        public string TransactionSlipPrinted { get; set; }
        public decimal TransactionTotal { get; set; }
        public decimal TransactionTotalInStatement { get; set; }
        public decimal FiscalTransactionTotal { get; set; }
        public int NextTransactionDetailLine { get; set; }
        public int Lines { get; set; }
        public int LinesOutstanding { get; set; }
        public int LinesReconciled { get; set; }
        public string TransactionStatus { get; set; }
        public decimal ReconciliationError { get; set; }
        public decimal ReconciliationErrorPending { get; set; }
        public decimal ReconciliationExchangeGain { get; set; }
        public decimal ReconciliationExchangeLoss { get; set; }
        public decimal ReconciliationAmount { get; set; }
        public decimal ReconciliationOutstandingAmt { get; set; }
        public string TransactionRecordedInSummary { get; set; }
        public decimal ReconciliationCreditCardCharg { get; set; }
        public decimal AmountCleared { get; set; }
        public decimal FunctionalTransactionAmount { get; set; }
        public decimal FunctionalTransactionTotal { get; set; }
        public decimal ReconciliationClearedAmount { get; set; }
        public decimal WriteOffAmount { get; set; }
        public decimal OutstandingAmount { get; set; }
        public string VarianceType { get; set; }
        public int LinesCanReverseInvoice { get; set; }
        public object ReconciliationDate { get; set; }
        public string ReconciliationStatus { get; set; }
        public string ReconciliationDescription { get; set; }
        public int LinesJournalled { get; set; }
        public int LinesPurged { get; set; }
        public int LinesProcessed { get; set; }
        public decimal ClearToFuturePeriod { get; set; }
        public decimal FiscalClearedToFuture { get; set; }
        public decimal FiscalClearedToCurrent { get; set; }
        public string ReconciledAndJournaledTransac { get; set; }
        public string PaymentPayeeName { get; set; }
        public string PaymentVendorName { get; set; }
        public string BankEntryTransferNumber { get; set; }
        public int LinesCreditCard { get; set; }
        public int LinesExchangeDifference { get; set; }
        public string ReverseInvoice { get; set; }
        public decimal ReconcilebyDetailReconciled { get; set; }
        public decimal ReconcilebyDetailOutstanding { get; set; }
        public decimal CurrentPeriodsWriteOff { get; set; }
        public decimal ClearToReconciliationPeriod { get; set; }
        public decimal FiscalWriteOffToThisPeriod { get; set; }
        public decimal FiscalRemainingOutstanding { get; set; }
        public decimal TotalDeltaWriteOffs { get; set; }
        public decimal TotalDeltaBankErrors { get; set; }
        public decimal TotalDeltaExchangeGain { get; set; }
        public decimal TotalDeltaExchangeLoss { get; set; }
        public decimal TotalDeltaCreditCardCharge { get; set; }
        public decimal TotalDeltaCleared { get; set; }
        public decimal TotalDeltaFunctionalAmount { get; set; }
        public string FunctionalCurrency { get; set; }
        public string StatementCurrency { get; set; }
        public decimal ReconciliationWriteOffSum { get; set; }
        public string ReconciliationpostingYear { get; set; }
        public int ReconciliationpostingPeriod { get; set; }
        public decimal TotalDeposits { get; set; }
        public decimal DepositsInTransit { get; set; }
        public decimal DepositFunctionalTotal { get; set; }
        public decimal SumOfDepositTotalWriteOffs { get; set; }
        public decimal TotalDepositBankErrors { get; set; }
        public decimal TotalDepositExchangeGain { get; set; }
        public decimal TotalDepositExchangeLoss { get; set; }
        public decimal TotalDepositCreditCardCharge { get; set; }
        public decimal TotalDepositCleared { get; set; }
        public decimal FiscalDepositWriteOffToThis { get; set; }
        public decimal FiscalDepositBankErrors { get; set; }
        public decimal FiscalDepositExchangeGain { get; set; }
        public decimal FiscalDepositExchangeLoss { get; set; }
        public decimal FiscalDepositCreditCardCharg { get; set; }
        public decimal FiscalDepositCleared { get; set; }
        public decimal DepositClearedwithExchangeRa { get; set; }
        public decimal DepositsInTransitToFiscalPeriod { get; set; }
        public decimal FiscalDepositClearedToFuture { get; set; }
        public decimal TotalChecks { get; set; }
        public decimal ChecksOutstanding { get; set; }
        public decimal WithdrawalFunctionalTotal { get; set; }
        public decimal SumOfWithdrawalTotalWriteOf { get; set; }
        public decimal TotalWithdrawalBankErrors { get; set; }
        public decimal TotalWithdrawalExchangeGain { get; set; }
        public decimal TotalWithdrawalExchangeLoss { get; set; }
        public decimal TotalWithdrawalCreditCardCha { get; set; }
        public decimal TotalWithdrawalCleared { get; set; }
        public decimal FiscalWithdrawalWriteOffToT { get; set; }
        public decimal FiscalWithdrawalBankErrors { get; set; }
        public decimal FiscalWithdrawalExchangeGain { get; set; }
        public decimal FiscalWithdrawalExchangeLoss { get; set; }
        public decimal FiscalWithdrawalCreditCardCh { get; set; }
        public decimal RECWPCLR { get; set; }
        public decimal ChecksClearedwithExchangeRateD { get; set; }
        public decimal ChecksOutstandingToFiscalPeriod { get; set; }
        public decimal FiscalWithdrawalClearedToFut { get; set; }
        public decimal FiscalMiscellaneousEntry { get; set; }
        public decimal PaymentMiscellaneousEntriesToFiscal { get; set; }
        public decimal DepositMiscellaneousEntriesToFiscal { get; set; }
        public decimal PaymentMiscellaneousEntriesToFuture { get; set; }
        public decimal DepositMiscellaneousEntriesToFuture { get; set; }
        public decimal FiscalDepositBookAmount { get; set; }
        public decimal FiscalWithdrawalBookAmount { get; set; }
        public string DetailAccessPortal { get; set; }
        public decimal ReconciliationDelta { get; set; }
        public string ProcessCommandCode { get; set; }
        public Banktransactiondetail[] BankTransactionDetails { get; set; }
        public string UpdateOperation { get; set; }
    }

    public class Banktransactiondetail
    {
        public string BankCode { get; set; }
        public int TransactionHeaderSerial { get; set; }
        public int TransactionDetailLine { get; set; }
        public string SourceApplication { get; set; }
        public string TransactionDetailStatus { get; set; }
        public string TransactionType { get; set; }
        public string DetailTransactionType { get; set; }
        public string RemittanceID { get; set; }
        public DateTime TransactionDate { get; set; }
        public int BatchNumber { get; set; }
        public int EntryNumber { get; set; }
        public int PostingSequenceNumber { get; set; }
        public string TransactionReference { get; set; }
        public string TransactionDescription { get; set; }
        public string PayerCode { get; set; }
        public string PayeeName { get; set; }
        public string VendorName { get; set; }
        public decimal SourceTransactionAmount { get; set; }
        public decimal FunctionalTransactionAmount { get; set; }
        public string ExchangeRateType { get; set; }
        public string ReceiptCurrency { get; set; }
        public DateTime ExchangeRateDate { get; set; }
        public int ExchangeRate { get; set; }
        public decimal RateSpread { get; set; }
        public string RateOperation { get; set; }
        public string DistributionCode { get; set; }
        public string GLAccount { get; set; }
        public int DrilldownType { get; set; }
        public long DrilldownLink { get; set; }
        public string ReconciliationStatus { get; set; }
        public object StatusChangeDate { get; set; }
        public string ReconciliationDescription { get; set; }
        public decimal ClearedAmount { get; set; }
        public object ReconciliationPostingDate { get; set; }
        public string ReconciliationPostingYear { get; set; }
        public string ReconciliationPostingPeriod { get; set; }
        public bool Reconciled { get; set; }
        public decimal RemainingInTransitAmount { get; set; }
        public string PaymentCode { get; set; }
        public string CheckStockCode { get; set; }
        public string OFXTransactionID { get; set; }
        public string FiscalYear { get; set; }
        public string FiscalPeriod { get; set; }
        public object ReversalReturnDate { get; set; }
        public string SourceDocumentNumber { get; set; }
        public string CanReverseInvoice { get; set; }
        public string ReverseInvoice { get; set; }
        public string ReconciledAndJournaledTransac { get; set; }
        public int PostingSequence { get; set; }
        public int EntryType { get; set; }
        public DateTime DocumentPostedDate { get; set; }
        public int LastReconciliationStatus { get; set; }
        public string ReconciledBy { get; set; }
        public decimal ReconciliationError { get; set; }
        public decimal ReconciliationErrorPending { get; set; }
        public decimal ReconciliationExchangeGain { get; set; }
        public decimal ReconciliationExchangeLoss { get; set; }
        public string ReconciliationSuggestion { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal OutstandingAmount { get; set; }
        public string ReconciliationTarget { get; set; }
        public string DistributionCodeDescription { get; set; }
        public string GLAccountDescription { get; set; }
        public decimal ReconciliationAmountDelta { get; set; }
        public int Line { get; set; }
        public int LineOutstanding { get; set; }
        public int LineReconciled { get; set; }
        public decimal ReconciliationCreditCardCharg { get; set; }
        public decimal WriteOffAmount { get; set; }
        public string FunctionalCurrency { get; set; }
        public string StatementCurrency { get; set; }
        public decimal SummatedTransactionAmount { get; set; }
        public decimal ReconciliationSpread { get; set; }
        public decimal FiscalTransactionRemainingIn { get; set; }
        public decimal FiscalOutstandingAmount { get; set; }
        public decimal FiscalWriteOffs { get; set; }
        public decimal FiscalBankErrors { get; set; }
        public decimal FiscalExchangeGain { get; set; }
        public decimal FiscalExchangeLoss { get; set; }
        public decimal FiscalCreditCardCharge { get; set; }
        public decimal FiscalCleared { get; set; }
        public decimal FiscalFunctionalAmount { get; set; }
        public decimal FiscalOriginalTransactionAmou { get; set; }
        public decimal TotalBookAmount { get; set; }
        public decimal FiscalBookAmount { get; set; }
        public decimal TotalRemainingAmount { get; set; }
        public decimal FiscalRemainingAmount { get; set; }
        public decimal FiscalWriteOffToThisPeriod { get; set; }
        public decimal FiscalClearedToFuture { get; set; }
        public decimal FiscalClearedToCurrent { get; set; }
        public decimal CurrentPeriodsWriteOff { get; set; }
        public decimal PostedFiscalClearedToFuture { get; set; }
        public int NumberOfDaysSinceReconciled { get; set; }
        public decimal StatementAmount { get; set; }
        public int LineCreditCard { get; set; }
        public int LineExchangeDifference { get; set; }
        public int LineCanReverseInvoice { get; set; }
        public int BankStatementType { get; set; }
        public string ReconciliationYear { get; set; }
        public int ReconciliationPeriod { get; set; }
        public decimal ReconcilebyDetailReconciled { get; set; }
        public decimal ReconcilebyDetailOutstanding { get; set; }
        public string UpdateOperation { get; set; }
    }

    public class Checkstock
    {
        public string BankCode { get; set; }
        public string CheckStockCode { get; set; }
        public string Description { get; set; }
        public int NextCheckNumber { get; set; }
        public string StockType { get; set; }
        public string CheckForm { get; set; }
        public string AdviceForm { get; set; }
        public int AdviceLinesPerPage { get; set; }
        public string Language { get; set; }
        public string UpdateOperation { get; set; }
    }

}
